language: node_js
node_js:
  - '12'
services:
  - mongodb
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=3000
    - MONGODB_URL=mongodb://localhost:27017/zkid-backend-alpha-v1
    - JWT_SECRET=thisisasamplesecret
    - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
